export const TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  STICKER_REPOSITORY: 'STICKER_REPOSITORY',
  STICKER_PACK_REPOSITORY: 'STICKER_PACK_REPOSITORY',
  USER_STICKER_REPOSITORY: 'USER_STICKER_REPOSITORY',
  UNIFIED_COLLECTION_REPOSITORY: 'UNIFIED_COLLECTION_REPOSITORY',
  PLATFORM_SETTING_REPOSITORY: 'PLATFORM_SETTING_REPOSITORY',
} as const;
