name: Docker API

on:
  push:
    branches: [main, master]
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'package.json'
      - 'package-lock.json'
      - '.dockerignore'
  pull_request:
    paths:
      - 'apps/**'
      - 'packages/**'
      - 'package.json'
      - 'package-lock.json'
      - '.dockerignore'
  workflow_dispatch:

jobs:
  build-image:
    name: Build imagem API
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/api/Dockerfile
          push: false
          tags: klipyt-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
